export const columns = {
    firstName: "Имя",
    lastName: "Фамилия",
    patronymic: "Отчество",
    phoneNumber: "Телефон",
    role: "Права доступа",
    organization: "Организация",
    email: "Почта",
    name: "Название",
    address: "Адрес",
    administratorFullName: "Администратор",
    key: "Название",
    lastModified: "Дата изменения",
    size: "Размер",
    studyDescription: "Описание",
    studyDate: "Дата",
    studyTime: "Время",
    seriesDescription: "Описание серии", 
    modality: "Модальность",
    patientId: "ID пациента",
    patientName: "Пациент",
    birthDate: "Дата рождения",
    studyId: "ID"
}